import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Inter as FontSans } from "next/font/google";
import "@/styles/globals.css";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import { QueryClientProviderWrapper } from "@/helper/querryclient-provider";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });
import { AuthContextProvider } from "@/context/Auth";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/helper/theme-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          fontSans.variable
        )}
      >
        <QueryClientProviderWrapper>
          <AuthContextProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
            <Toaster />
          </AuthContextProvider>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
